version: "3"

networks:
  hnt_monitor:
    driver: bridge
    ipam:
      config:
        - subnet: 10.30.0.0/24

services:
  hnt_monitor:
    container_name: hnt_monitor
    image: hnt_monitor:latest
    restart: always
    build:
      dockerfile: ./build/docker/hnt_monitor/Dockerfile
      context: .
    environment:
      DO_NOT_REMOVE: "setup"
      HNT_PROMETHEUS_PG_HOST: "http://prometheus_pushgateway:9091"
    networks:
      hnt_monitor:
        ipv4_address: 10.30.0.05
    depends_on:
      - prometheus_pushgateway

  prometheus_pushgateway:
    container_name: prometheus_pushgateway
    image: prom/pushgateway
    restart: always
    ports:
      - "9091:9091"
    networks:
      hnt_monitor:
        ipv4_address: 10.30.0.04

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    networks:
      hnt_monitor:
        ipv4_address: 10.30.0.03
    volumes:
      - ./src/conf/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      hnt_monitor:
        ipv4_address: 10.30.0.02

#  elasticsearch:
#    restart: always
#    container_name: elasticsearch
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.19
#    command: "elasticsearch -Enetwork.host=0.0.0.0 -Enode.name='logging' -Etransport.host=0.0.0.0 -Ediscovery.zen.minimum_master_nodes=1 -Egateway.recover_after_time=5s -Expack.security.enabled='false'"
#    ports:
#      - 9200:9200
#    networks:
#      hnt_monitor:
#        ipv4_address: 10.30.0.06
#
#  kibana:
#    restart: always
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:6.8.19
#    environment:
#      ELASTICSEARCH_URL: "http://elasticsearch:9200"
#      XPACK_MONITORING_ENABLED: "true"
#      XPACK_SECURITY_ENABLED: "false"
#    ports:
#      - 5602:5601
#    depends_on:
#      - elasticsearch
#    networks:
#      hnt_monitor:
#        ipv4_address: 10.30.0.07
#        
#  nginx-api:
#    container_name: nginx-api
#    image: nginx-api
#    build:
#      context: ./build/docker/nginx-api/
#    restart: always
#    ports:
#      - "443:443"
#    networks:
#      hnt_monitor:
#        ipv4_address: 10.30.0.08
